- name: Install pip applications
  pip:
    name:
      - ansible
      - ansible-lint
      - ansible-playbook-grapher
      - pip
      - psutil
    state: latest
    extra_args: --break-system-packages
