- name: Accept virtualbox-ext-pack license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: "true"
    vtype: select

- name: Install applications
  apt:
    force_apt_get: yes
    name:
      - audacity
      - baobab
      - blender
      - dconf-editor
      - deja-dup
      - gimp
      - gnome-calculator
      - gnome-shell-extension-prefs
      - gnome-tweaks
      - inkscape
      - libreoffice
      - peek
      - rhythmbox
      - simple-scan
      - totem
      - virtualbox
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
      - vlc
