- name: Accept virtualbox-ext-pack license
  command:
    cmd: debconf-set-selections
    stdin: virtualbox-ext-pack virtualbox-ext-pack/license select true

- name: Install applications
  apt:
    force_apt_get: yes
    name:
      - audacity
      - baobab
      - blender
      - dconf-editor
      - deja-dup
      - gimp
      - gnome-calculator
      - gnome-shell-extension-prefs
      - gnome-software
      - gnome-tweaks
      - inkscape
      - libreoffice
      - obs-studio
      - peek
      - rhythmbox
      - simple-scan
      - steam
      - totem
      - virtualbox
      - virtualbox-ext-pack
      - virtualbox-guest-additions-iso
      - vlc
