- name: Configure vim
  blockinfile:
    path: "{{ ansible_user_dir }}/.vimrc"
    create: yes
    mode: 0644
    marker: "\" {mark} ANSIBLE MANAGED BLOCK"
    block: |
      set expandtab
      set shiftwidth=2
      set softtabstop=2
      syntax on
