- name: Disable desktop-icons extension
  command: gnome-extensions disable desktop-icons@csoriano

- name: Show week numbers in calendar
  dconf:
    key: "/org/gnome/desktop/calendar/show-weekdate"
    value: "true"

- name: Show weekday in top bar
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"

- name: Enable dark theme
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Yaru-dark'"

- name: Enable window minimize on click
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/click-action"
    value: "'minimize-or-previews'"

- name: Enable night light
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"

- name: Set manual night light schedule
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic"
    value: "false"

- name: Set night light start time
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from"
    value: "18.0"

- name: Set night light end time
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-to"
    value: "6.0"

- name: Set night light temperature
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
    value: "uint32 4700"
