- name: Readable interface names
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX="
    line: GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
  notify: Regenerate grub config
